spring.application.name=StuEventManagement_Application

# Server configuration
server.port=${PORT:8080}

# MongoDB configuration (Ensure you set MONGO_URL in Railway environment variables)
spring.data.mongodb.uri=${MONGO_URL:mongodb+srv://ruushekas_db_user:qePkZ2KBWaOrjArH@cluster0.ldduwln.mongodb.net/student_events_db?retryWrites=true&w=majority}
